package modelo;
// Generated 1/03/2016 10:47:48 PM by Hibernate Tools 4.3.1



/**
 * Contrase�a generated by hbm2java
 */
public class Contraseña  implements java.io.Serializable {


     private int numcuenta;
     private String contraseña;

    public Contraseña() {
    }

	
    public Contraseña(int numcuenta) {
        this.numcuenta = numcuenta;
    }
    public Contraseña(int numcuenta, String contraseña) {
       this.numcuenta = numcuenta;
       this.contraseña = contraseña;
    }
   
    public int getNumcuenta() {
        return this.numcuenta;
    }
    
    public void setNumcuenta(int numcuenta) {
        this.numcuenta = numcuenta;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }




}


