package modelo;
// Generated 1/03/2016 10:47:48 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int numcuenta;
     private String nombre;
     private String correo;

    public Usuario() {
    }

	
    public Usuario(int numcuenta) {
        this.numcuenta = numcuenta;
    }
    public Usuario(int numcuenta, String nombre, String correo) {
       this.numcuenta = numcuenta;
       this.nombre = nombre;
       this.correo = correo;
    }
   
    public int getNumcuenta() {
        return this.numcuenta;
    }
    
    public void setNumcuenta(int numcuenta) {
        this.numcuenta = numcuenta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


